package(default_visibility = ["//visibility:public"])

exports_files(["FrutaApp.swift"])

filegroup(
    name = "SharedSources",
    srcs = glob(
        ["**/*.swift"],
        exclude = ["FrutaApp.swift"],
    ),
)
